[theme]
primaryColor = "#ff4b91"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
maxUploadSize = 200
runOnSave = false

[browser]
gatherUsageStats = false
